apiVersion: v1
kind: Pod
metadata:
  name: nginx-giropops
  labels:
    run: nginx-giropops
    app: giropops-strigus
spec:
  containers:
  - name: nginx-giropops
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.3"
        memory: "440Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
